name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *"   # Runs daily at 18:00 UTC
  workflow_dispatch:         # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 10
          SETTING_JSON: |
            {
              "githubUserName": "notnamansinha",
              "startForeColor": "#58A6FF",
              "endForeColor": "#FF6E40",
              "foreColorAnimate": true,
              "backColor": "#0d1117",
              "dotColor": "#58A6FF",
              "guideColor": "gray",
              "layoutDirection": "LEFT_TOP_RIGHT",
              "dayOfWeeks": 0,
              "type": "normal",
              "utcOffset": "+05:30"
            }

      - name: Commit & Push 3D SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "chore: regenerate 3D contribution graph [skip ci]"; then
            git push
          fi
